#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EncryptoBot_Proj.Resource", IsApplication=true)]

namespace EncryptoBot_Proj
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int green_black_gradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int keywords = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int lock_key = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int SplashImgLarge = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Unlock = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int DecryptActv_Btn = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int EncryptActv_Btn = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int KeyActv_Btn = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int copyButton = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int cyptButton = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int encryptedText = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int keyEdit = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int keyView = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int listView = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int originalText = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Key_Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
